(function(){
  const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],clone=o=>JSON.parse(JSON.stringify(o)),colors=['#00e5ff','#ff2975','#b9ff38','#ffbd2e','#8a7dff','#42ffb0','#ff7043'];
  window.appEngine=new AudioEngine();const visual=new Visualizer($('#scope'));let state={name:'先バレ',layers:clone(PulsePresets['先バレ'].layers)},selected=0,history=[],future=[],toastTimer;
  const fields=[['wave','波形','select',['sine','square','sawtooth','triangle','noise']],['startFrequency','開始周波数',20,12000,1,' Hz'],['endFrequency','終了周波数',20,12000,1,' Hz'],['startTime','開始タイミング',0,3,.01,' 秒'],['duration','音の長さ',.02,3,.01,' 秒'],['volume','音量',0,.85,.01,''],['attack','アタック',0,1,.005,' 秒'],['decay','ディケイ',0,1,.005,' 秒'],['sustain','サステイン',0,1,.01,''],['release','リリース',.01,2,.01,' 秒'],['pitchSweep','ピッチ変化',-12000,12000,10,' Hz'],['delay','ディレイ',0,.6,.01,' 秒'],['reverb','リバーブ',0,1,.01,''],['distortion','歪み',0,100,1,' %'],['lowpass','ローパス',80,12000,10,' Hz'],['highpass','ハイパス',20,6000,10,' Hz'],['pan','パン',-1,1,.01,'']];
  function notify(s){const names={ALERT:'警報',PREMIUM:'プレミアム',IMPACT:'衝撃',BASS:'重低音',FREEZE:'フリーズ',RUSH:'高速連打',CYBER:'サイバー',RETRO:'レトロ',HORROR:'ホラー'};s=s.replace(/(ALERT|PREMIUM|IMPACT|BASS|FREEZE|RUSH|CYBER|RETRO|HORROR) GENERATED/,(_,x)=>`${names[x]}サウンドを生成しました`);$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),1800)}function save(){localStorage.setItem('neonPulseLab',JSON.stringify(state))}function snapshot(){history.push(clone(state));if(history.length>60)history.shift();future=[]}function commit(){save();renderLayers();renderSequence();schedulePreview()}
  function presetButtons(){const g=$('#presetGrid');Object.entries(PulsePresets).forEach(([name,p])=>{const b=document.createElement('button');b.className='preset';b.innerHTML=`<small>${p.category}</small><b>${name}</b>`;b.onclick=()=>{snapshot();state={name,layers:clone(p.layers)};selected=0;commit();renderEditor();play();$$('.preset').forEach(x=>x.classList.toggle('active',x===b))};g.append(b)})}
  function renderEditor(){const l=state.layers[selected];if(!l)return;$('#editingLabel').textContent=`EDITING LAYER ${String(selected+1).padStart(2,'0')}`;const e=$('#editor');e.innerHTML='';fields.forEach(f=>{const [key,label,typeOrMin,max,step,suffix='']=f,d=document.createElement('div');d.className='control';if(typeOrMin==='select'){d.innerHTML=`<label>${label}<output>${l[key]}</output></label><select data-key="${key}">${max.map(x=>`<option ${x===l[key]?'selected':''}>${x}</option>`).join('')}</select>`}else d.innerHTML=`<label>${label}<output>${Number(l[key]).toFixed(step<.01?3:step<1?2:0)}${suffix}</output></label><input type="range" data-key="${key}" min="${typeOrMin}" max="${max}" step="${step}" value="${l[key]}">`;e.append(d)});e.querySelectorAll('input,select').forEach(inp=>{inp.onpointerdown=()=>snapshot();inp.onchange=inp.oninput=()=>{const key=inp.dataset.key;state.layers[selected][key]=inp.tagName==='SELECT'?inp.value:Number(inp.value);if(key==='endFrequency'||key==='startFrequency')state.layers[selected].pitchSweep=state.layers[selected].endFrequency-state.layers[selected].startFrequency;if(key==='pitchSweep')state.layers[selected].endFrequency=Math.max(20,Math.min(12000,state.layers[selected].startFrequency+state.layers[selected].pitchSweep));const out=inp.parentElement.querySelector('output');out.textContent=inp.value+(fields.find(x=>x[0]===key)?.[5]||'');save();renderLayers();renderSequence();schedulePreview()}})}
  function renderLayers(){const list=$('#layerList');list.innerHTML='';state.layers.forEach((l,i)=>{const d=document.createElement('div');d.className='layer-card'+(i===selected?' selected':'');d.style.setProperty('--layer',colors[i%colors.length]);d.innerHTML=`<div class="layer-top"><span class="layer-number">${String(i+1).padStart(2,'0')}</span><div class="layer-info"><b>${l.name}</b><small>${l.wave.toUpperCase()} / ${Math.round(l.startFrequency)}→${Math.round(l.endFrequency)}Hz</small></div><span class="switch ${l.enabled?'on':''}" data-action="toggle"></span><div class="layer-actions"><button data-action="copy" title="複製">⧉</button><button data-action="delete" title="削除">×</button></div></div><div class="layer-mini"><span>START <b>${l.startTime.toFixed(2)}s</b></span><span>LENGTH <b>${l.duration.toFixed(2)}s</b></span></div>`;d.onclick=e=>{const a=e.target.dataset.action;if(a){e.stopPropagation();snapshot();if(a==='toggle')l.enabled=!l.enabled;if(a==='copy'&&state.layers.length<16){const n=clone(l);n.id=crypto.randomUUID();n.name+=' COPY';n.startTime=Math.min(3,n.startTime+.1);state.layers.splice(i+1,0,n);selected=i+1}if(a==='delete'&&state.layers.length>1){state.layers.splice(i,1);selected=Math.max(0,Math.min(selected,state.layers.length-1))}commit();renderEditor()}else{selected=i;renderLayers();renderEditor()}};list.append(d)})}
  function renderSequence(){const box=$('#sequenceTracks');box.innerHTML='';state.layers.forEach((l,i)=>{const t=document.createElement('div');t.className='track';t.innerHTML=`<span class="track-label">${String(i+1).padStart(2,'0')} ${l.name}</span><div class="track-lane"><div class="track-block" style="--c:${colors[i%colors.length]};left:${l.startTime/3*100}%;width:${Math.max(1,l.duration/3*100)}%"></div></div>`;box.append(t)})}
  let previewTimer;function schedulePreview(){clearTimeout(previewTimer);previewTimer=setTimeout(async()=>{try{const b=await appEngine.render(state),d=b.getChannelData(0),arr=new Uint8Array(600);for(let i=0;i<arr.length;i++)arr[i]=128+d[Math.floor(i*d.length/arr.length)]*120;visual.setPreview(arr)}catch(e){}},250)}
  async function play(){try{$('#statusText').textContent='音声を生成中';await appEngine.play(state,$('#loopToggle').checked);visual.setAnalyser(appEngine.analyser);$('#statusText').textContent='音声出力中'}catch(e){notify('再生エラー: '+e.message)}}
  function randomize(){
    snapshot();const cat=$('#randomCategory').value,r=(a,b)=>a+Math.random()*(b-a);
    const profiles={Alert:{waves:['square','sawtooth','sine'],range:[500,4200],count:[4,8]},Premium:{waves:['sine','triangle'],range:[700,9000],count:[4,8]},Impact:{waves:['noise','sine','sawtooth'],range:[30,1400],count:[4,8]},Cyber:{waves:['sawtooth','square','noise'],range:[180,7800],count:[4,8]},Retro:{waves:['square','triangle'],range:[110,2200],count:[4,8]},Horror:{waves:['sine','noise','sawtooth'],range:[25,1800],count:[4,8]},Bass:{waves:['sine','triangle','noise'],range:[24,320],count:[4,7]},Freeze:{waves:['noise','sawtooth','sine','square'],range:[180,6200],count:[5,9]},Rush:{waves:['square','sawtooth','triangle'],range:[260,4800],count:[7,12]}};
    const p=profiles[cat],count=Math.floor(r(...p.count)),labels={Alert:'警報',Premium:'プレミアム',Impact:'衝撃',Bass:'重低音',Freeze:'フリーズ',Rush:'高速連打',Cyber:'サイバー',Retro:'レトロ',Horror:'ホラー'};
    state={name:`ランダム ${labels[cat]}`,layers:Array.from({length:count},(_,i)=>{const a=r(...p.range),isBass=cat==='Bass',isFreeze=cat==='Freeze',isRush=cat==='Rush';let b=Math.max(20,Math.min(12000,a*(Math.random()>.42?r(1.2,4.5):r(.15,.8)))),start=r(0,Math.min(2.7,i*.22+.18)),duration=r(.05,.55);if(isBass){b=r(20,Math.min(a,95));start=r(0,.45);duration=r(.22,1.05)}if(isFreeze){b=i===0?r(24,90):r(20,Math.max(30,a*.45));start=i===0?0:r(.04,.75);duration=i===0?r(.05,.12):r(.12,.8)}if(isRush){b=Math.min(12000,a*r(.8,1.8));start=i*r(.055,.12);duration=r(.035,.13)}return makeLayer(`${labels[cat]} ${i+1}`,p.waves[Math.floor(Math.random()*p.waves.length)],a,b,duration,r(isBass?.24:.1,isBass?.68:.55),start,{delay:isRush?0:Math.random()>.6?r(.03,.16):0,reverb:isFreeze?r(.25,.78):r(0,cat==='Premium'?.7:.35),distortion:isBass?r(8,32):cat==='Impact'?r(12,48):r(0,18),lowpass:isBass?r(120,700):r(Math.max(300,a),12000),highpass:isBass?20:r(20,Math.min(1000,a)),pan:isBass?r(-.18,.18):isRush?r(-.75,.75):r(-.6,.6)})})};selected=0;commit();renderEditor();play();notify(`${cat.toUpperCase()} GENERATED`)
  }
  $('#playBtn').onclick=play;$('#stopBtn').onclick=()=>{appEngine.stop();$('#statusText').textContent='音声停止中'};$('#regenerateBtn').onclick=play;$('#randomBtn').onclick=randomize;$('#addLayer').onclick=()=>{if(state.layers.length>=16)return notify('最大16レイヤーです');snapshot();state.layers.push(makeLayer(`レイヤー ${state.layers.length+1}`,'sine',440,880,.25,.3,.1));selected=state.layers.length-1;commit();renderEditor()};
  $('#exportWav').onclick=async()=>{notify('WAVを書き出し中…');const b=await appEngine.render(state);WavExporter.download(WavExporter.encodeWav(b),`original_${state.name.replace(/[^a-zA-Z0-9ぁ-んァ-ヶ一-龠]/g,'_')}_${String(Date.now()).slice(-3)}.wav`);notify('WAVを保存しました（44.1kHz / 16bit）')};
  $('#exportPreset').onclick=()=>WavExporter.download(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),`my_${state.name.replace(/\s/g,'_')}.json`);$('#importPreset').onclick=()=>$('#presetFile').click();$('#presetFile').onchange=async e=>{try{const raw=JSON.parse(await e.target.files[0].text()),next=appEngine.normalize(raw);snapshot();state={name:raw.name||'読込プリセット',layers:next.layers};selected=0;commit();renderEditor();notify('プリセットを読み込みました')}catch(err){notify('無効なJSONです')}};
  function undo(){if(!history.length)return;future.push(clone(state));state=history.pop();selected=Math.min(selected,state.layers.length-1);commit();renderEditor()}function redo(){if(!future.length)return;history.push(clone(state));state=future.pop();selected=Math.min(selected,state.layers.length-1);commit();renderEditor()}$('#undoBtn').onclick=undo;$('#redoBtn').onclick=redo;document.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}if(e.ctrlKey&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}});$$('[data-view]').forEach(b=>b.onclick=()=>{$$('[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');visual.setMode(b.dataset.view)});
  const originalRenderEditor=renderEditor;renderEditor=function(){originalRenderEditor();$('#editingLabel').textContent=`レイヤー ${String(selected+1).padStart(2,'0')} を編集中`};
  const layerNames={'SUB IMPACT':'低音インパクト','RISING ARC':'上昇アーク','NEON TICK':'高音アクセント','TAIL':'残響','GLASS RISE':'グラス上昇音','HARMONIC':'倍音','SPARK 1':'スパーク 1','SPARK 2':'スパーク 2','NOISE HIT':'ノイズ衝撃','SUB DROP':'低音降下','METAL SNAP':'金属アクセント','ROOM':'空間残響','ALARM A':'警報 A','ALARM B':'警報 B','ALARM A2':'警報 A2','ALARM B2':'警報 B2','FANFARE':'ファンファーレ','SHIMMER':'きらめき','CHIME A':'チャイム A','CHIME B':'チャイム B','CHIP LEAD':'チップリード','ARPEGGIO 1':'アルペジオ 1','ARPEGGIO 2':'アルペジオ 2','ARPEGGIO 3':'アルペジオ 3','WHITE BURST':'ホワイトバースト','LASER':'レーザー','CLICK':'クリック','AFTERGLOW':'余韻','VIBE CORE':'低音コア','RUMBLE':'振動ノイズ','PULSE':'パルス','BODY':'低音ボディ'};
  const originalRenderLayers=renderLayers;renderLayers=function(){originalRenderLayers();$$('.layer-mini span').forEach(x=>{x.innerHTML=x.innerHTML.replace('START','開始').replace('LENGTH','長さ').replaceAll('s</b>','秒</b>')});$$('.layer-info b').forEach(x=>x.textContent=layerNames[x.textContent]||x.textContent)};
  const originalPresetButtons=presetButtons;presetButtons=function(){originalPresetButtons();const categories=['警報演出','高音上昇','衝撃','警告','祝福演出','レトロ','サイバー','重低音'];$$('.preset small').forEach((x,i)=>x.textContent=categories[i])};
  try{const old=JSON.parse(localStorage.getItem('neonPulseLab'));if(old?.layers?.length)state={name:old.name||'復元データ',layers:appEngine.normalize(old).layers}}catch(e){}presetButtons();renderLayers();renderEditor();renderSequence();schedulePreview();
})();
