(function(){
  const clamp=(v,a,b)=>Math.min(b,Math.max(a,Number(v)||0));
  class AudioEngine{
    constructor(){this.ctx=null;this.active=[];this.loopTimer=null;this.master=null;this.analyser=null}
    async ensure(){if(!this.ctx){this.ctx=new (window.AudioContext||window.webkitAudioContext)({sampleRate:44100});this.buildMaster(this.ctx)}if(this.ctx.state==='suspended')await this.ctx.resume();return this.ctx}
    buildMaster(ctx,destination=ctx.destination){const input=ctx.createGain(),comp=ctx.createDynamicsCompressor(),master=ctx.createGain();comp.threshold.value=-12;comp.knee.value=16;comp.ratio.value=12;comp.attack.value=.003;comp.release.value=.18;master.gain.value=.72;input.connect(comp);comp.connect(master);master.connect(destination);if(ctx instanceof AudioContext){this.analyser=ctx.createAnalyser();this.analyser.fftSize=2048;master.connect(this.analyser);this.master=input}return input}
    normalize(config){return {version:1,name:config.name||'Untitled Pulse',layers:(config.layers||[]).slice(0,16).map((x,i)=>({id:x.id||crypto.randomUUID(),name:x.name||`LAYER ${i+1}`,enabled:x.enabled!==false,wave:['sine','square','sawtooth','triangle','noise'].includes(x.wave)?x.wave:'sine',startFrequency:clamp(x.startFrequency??x.frequency??440,20,12000),endFrequency:clamp(x.endFrequency??x.startFrequency??x.frequency??440,20,12000),duration:clamp(x.duration??.25,.02,3),volume:clamp(x.volume??.3,0,.85),startTime:clamp(x.startTime??0,0,3),attack:clamp(x.attack??.005,0,1),decay:clamp(x.decay??.08,0,1),sustain:clamp(x.sustain??.6,0,1),release:clamp(x.release??.1,.01,2),pitchSweep:clamp(x.pitchSweep??0,-12000,12000),delay:clamp(x.delay??0,0,.6),reverb:clamp(x.reverb??0,0,1),distortion:clamp(x.distortion??0,0,100),lowpass:clamp(x.lowpass??12000,80,12000),highpass:clamp(x.highpass??20,20,6000),pan:clamp(x.pan??0,-1,1)}))}}
    curve(amount){const n=1024,c=new Float32Array(n),k=amount*4;for(let i=0;i<n;i++){const x=i*2/n-1;c[i]=(1+k)*x/(1+k*Math.abs(x))}return c}
    impulse(ctx,seconds=1.2){const len=Math.floor(ctx.sampleRate*seconds),b=ctx.createBuffer(2,len,ctx.sampleRate);for(let c=0;c<2;c++){const d=b.getChannelData(c);for(let i=0;i<len;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/len,2.5)}return b}
    scheduleLayer(ctx,dest,l,base=ctx.currentTime){if(!l.enabled)return;const t=base+l.startTime,d=l.duration,r=l.release;let src;if(l.wave==='noise'){const b=ctx.createBuffer(1,Math.ceil((d+r)*ctx.sampleRate),ctx.sampleRate),data=b.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;src=ctx.createBufferSource();src.buffer=b}else{src=ctx.createOscillator();src.type=l.wave;src.frequency.setValueAtTime(l.startFrequency,t);src.frequency.exponentialRampToValueAtTime(Math.max(20,l.endFrequency),t+d)}
      const gain=ctx.createGain(),hp=ctx.createBiquadFilter(),lp=ctx.createBiquadFilter(),pan=ctx.createStereoPanner(),dry=ctx.createGain();hp.type='highpass';hp.frequency.value=l.highpass;lp.type='lowpass';lp.frequency.value=Math.max(l.highpass+20,l.lowpass);pan.pan.value=l.pan;dry.gain.value=1;let node=src;node.connect(hp);hp.connect(lp);node=lp;if(l.distortion>0){const sh=ctx.createWaveShaper();sh.curve=this.curve(l.distortion);sh.oversample='2x';node.connect(sh);node=sh}node.connect(gain);gain.connect(pan);pan.connect(dry);dry.connect(dest);
      if(l.delay>0){const delay=ctx.createDelay(.8),fb=ctx.createGain();delay.delayTime.value=l.delay;fb.gain.value=.24;pan.connect(delay);delay.connect(fb);fb.connect(delay);delay.connect(dest)}if(l.reverb>0){const conv=ctx.createConvolver(),wet=ctx.createGain();conv.buffer=this.impulse(ctx,.7+l.reverb);wet.gain.value=l.reverb*.45;pan.connect(conv);conv.connect(wet);wet.connect(dest)}
      const a=Math.min(l.attack,d*.45),dec=Math.min(l.decay,d*.45),hold=Math.max(t+a+dec,t+d);gain.gain.setValueAtTime(.0001,t);gain.gain.exponentialRampToValueAtTime(Math.max(.0001,l.volume),t+a+.001);gain.gain.exponentialRampToValueAtTime(Math.max(.0001,l.volume*l.sustain),t+a+dec+.002);gain.gain.setValueAtTime(Math.max(.0001,l.volume*l.sustain),hold);gain.gain.exponentialRampToValueAtTime(.0001,hold+r);src.start(t);src.stop(hold+r+.02);this.active.push(src)}
    async generateSoundFromConfig(config,opts={}){const c=this.normalize(config),ctx=opts.context||await this.ensure(),dest=opts.destination||this.master||ctx.destination,base=opts.baseTime??ctx.currentTime+.015;c.layers.forEach(l=>this.scheduleLayer(ctx,dest,l,base));return c}
    async play(config,loop=false){this.stop();await this.generateSoundFromConfig(config);if(loop){const total=Math.max(.25,...config.layers.map(l=>l.startTime+l.duration+l.release))+.15;this.loopTimer=setInterval(()=>this.generateSoundFromConfig(config),total*1000)}}
    stop(){this.active.forEach(s=>{try{s.stop()}catch(e){}});this.active=[];clearInterval(this.loopTimer);this.loopTimer=null}
    async render(config){const c=this.normalize(config),length=Math.max(.5,...c.layers.map(l=>l.startTime+l.duration+l.release))+1.2,ctx=new OfflineAudioContext(2,Math.ceil(length*44100),44100),dest=this.buildMaster(ctx,ctx.destination);this.active=[];await this.generateSoundFromConfig(c,{context:ctx,destination:dest,baseTime:0});return ctx.startRendering()}
  }
  window.AudioEngine=AudioEngine;window.generateSoundFromConfig=(config)=>window.appEngine.generateSoundFromConfig(config);
})();
